# Generated by Django 5.0.2 on 2024-02-18 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoice_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Invoice_details",
            new_name="InvoiceDetail",
        ),
    ]
